### PR TITLE
Update Outdated Twitter Logo to Current Branding

### LINKED ISSUE #554: Update Outdated Twitter Logo to Current Branding
## 🎉 Description

The repository is currently using an old version of the Twitter logo. We need to update it to the latest version as per Twitter's branding guidelines.

## 🔢 Steps To Reproduce Issue 

Navigate to [Decentraland Marketplace](https://decentraland.org/marketplace/).
Scroll down to the bottom of the page.
Observe the Twitter logo in the footer section.

##  Screenshots
image

##  Action Required:

Replace old logos with the new ones.
Ensure all instances are updated.

##  Expected Result:

All instances of the old Twitter logo in the repository are replaced with the new logo.

### PR DESCRIPTION
**Pull request by Jagadeeshftw**
## Description
This PR addresses the issue of updating the Twitter icon to the latest version by updating the Twitter SVG icon.

## Related Issue
Fixes #554 

## Changes Made
Verified and updated the Twitter SVG icon in the assets.
Replaced the outdated SVG with the latest version of the Twitter icon.

### Dark mode:
image
### Light mode:
image

### CODE REVIEW

**Comment by Jagadeeshftw** [comment]
@LautaroPetaccio Can please review this?

**Review by kevinszuchet — APPROVED** [review]
LGTM!

Thank you for the help @Jagadeeshftw

**Comment by kevinszuchet** [comment]
Hey @Jagadeeshftw,

I noticed that the first commit is not signed, which is preventing the PR from being available for merge. Could you please sign it? This is a requirement from the base branch. 🙏 

Thanks again for your help!

**Comment by kevinszuchet** [comment]
Maybe this can help https://stackoverflow.com/a/59351278

**Comment by Jagadeeshftw** [comment]
Is it fine now @kevinszuchet ?

**Comment by kevinszuchet** [comment]
Could you try leaving only the original commit that is now correctly signed?

**Comment by Jagadeeshftw** [comment]
Let me create new PR

**Pull request closed without merging**
