### PR TITLE
fix: 1400 vulns and react deprecation warning

### PR DESCRIPTION
**Pull request by eordano**

### CODE REVIEW

**Comment by cazala** [comment]
@eordano what is the purpose of `newTiles` in the state and the `forceUpdate` added to the handler? Does it workaround something that could be fix by changing the Atlas to be a `Component` instead of a `PureComponent` maybe?

**Comment by eordano** [comment]
I tried to be as close as the original implementation as possible. My two
cents: it feels a little hot-wired (both the before and after). I'd try to
propose a new interface but I was trying to keep the same outbound
interface and behavior...

**Comment by cazala** [comment]
@eordano ok, I understand why removing `componentWillReceiveProps` to prevent warnings, what I don't think I understand is why adding `newTiles`, `getDerivedStateFromProps` and `forceUpdate`, they can be removed all together and the Atlas should work as before, or am I missing something?

I think it is easier to explain it with code, so I made a PR to this branch, you can see it here: #51

**Pull request merged**
